### ISSUE TITLE
Feature Request - Config Item for no smoke

### ISSUE THREAD

**Issue by BrianBoundy** [TastyChickenLegs/NoSmokeStayLit#1]
I would love to use this to keep my fireplaces on all day, but I do like the smoke effect. Could you add a toggle for smoke like you do for using fuel so I can not turn off the smoke?

I tried your timed torches, but then my fireplace can't be used during the day.

**Comment by TastyChickenLegs** [comment]
I had this feature in my timed torches and took it out.  I will look to add it back there as it's a much simpler mod to modify.  I will let you know.

**Comment by TastyChickenLegs** [comment]
Added in 2.2.0 uploaded this morning.
