### ISSUE TITLE
Bug ver 1.1.5 - Console spam and all lights off

### ISSUE THREAD

**Issue by DaveKX** [TastyChickenLegs/NoSmokeStayLit#2]
Hello, with both 1.1.4 and 1.1.5 versions I'm getting the same bug apparently. All lights are off when I join the world, and console starts spamming this error: 
```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NoSmokeStayLit.NoSmokeStayLit+FireplaceIsBurning_Patch.Postfix (Fireplace __instance, System.Boolean& __result, UnityEngine.GameObject& ___m_enabledObjectHigh, ZNetView& ___m_nview) (at <e1b58e842ac54a7cab6b1a8702a204a6>:0)
(wrapper dynamic-method) Fireplace.DMD<Fireplace::IsBurning>(Fireplace)
(wrapper dynamic-method) Fireplace.DMD<Fireplace::UpdateFireplace>(Fireplace)
```

[LogOutput.log](https://github.com/TastyChickenLegs/NoSmokeStayLit/files/10255066/LogOutput.log)

**Comment by TastyChickenLegs** [comment]
Let me take a look.  I don't personally use that portion of the mod but will run it tonight and see what I  can find.  Thanks for letting me know.

**Comment by TastyChickenLegs** [comment]
Honestly I worked with this for about an hour in every configuration and could not replicate the problem.  Try deleting the config file and letting the mod recreate the file.  This is clearly coming from the new code that take away the smoke for braziers but I cannot recreate the error on my side.  If deleting the file doesn't work for you let me know.  I will add and error catch that fix the problem permanently and post a new version this weekend.

**Comment by TastyChickenLegs** [comment]
[NoSmokeStayLit.zip](https://github.com/TastyChickenLegs/NoSmokeStayLit/files/10290726/NoSmokeStayLit.zip)

Try this and see if it fixed your issue.  Unzip it and put the file in your plugin directory for BepInex

**Comment by DaveKX** [comment]
Hey! I tried what you first said (deleting the config file) and it actually worked, bruh, now I feel kinda bad for coming here when it was just that. I always thought that when I update a mod it recreates the config file automatically, so this thought didn't even cross my mind... But thank you for your time! Idk if it's still needed to test this new dll you sent, but if you want me to test it I will :)

**Comment by TastyChickenLegs** [comment]
Hey it's fine.  I am glad you got it fixed.  You don't have to test the dll.  I just added an error catch which should have been in there anyways.  I will probably update it soon with that change.  Thanks again and glad you are using my mod.
