### ISSUE TITLE
Odin's campsite fire/stone oven

### ISSUE THREAD

**Issue by irischman** [TastyChickenLegs/NoSmokeStayLit#3]
Just a heads up.  Thanks for the mod. 

> all fire sources can be added
> 
> Custom modded items can be added as well..

I'm not sure if the above note is suggesting that adding item ids should work or that you would add them.  But I tried to add the stone oven from the base game and the mini fire pit from the Campsite mod and couldn't get either to work.

The oven had no discernable change, while the mini campfire's tooltip listed your mod as if it was registered but would not light and I received the following error.

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
NoSmokeStayLit.NoSmokeStayLit+FireplaceIsBurning_Patch.Postfix (Fireplace __instance, System.Boolean& __result, UnityEngine.GameObject& ___m_enabledObjectHigh, ZNetView& ___m_nview) (at <e1b58e842ac54a7cab6b1a8702a204a6>:0)
(wrapper dynamic-method) Fireplace.DMD<Fireplace::IsBurning>(Fireplace)
Fireplace.UpdateFireplace () (at <35c0f7aa1999477788815a7bf78200d7>:0)

**Comment by irischman** [comment]
Fixed with newest update

**Comment by TastyChickenLegs** [comment]
Sorry I missed this. I need to turn on notifications from Github.  Glad it's fixed.
