### ISSUE TITLE
Still able to add wood to fireplaces, hearth, etc

### ISSUE THREAD

**Issue by DaveKX** [TastyChickenLegs/NoSmokeStayLit#4]
Even with the eternal fuel enabled, we can add fuel manually clicking in the keybind, and although that would not be a problem for people because obviously if you enable eternal fuel, you would not add fuel to it (xD), it conflicts with mods that adds fuel automatically from containers, like your other mod 'AutomaticFuel', because they keep fueling even with the eternal fuel option enabled. Would you be able to make so no fuel can be added to the fireplaces, torches, etc? FuelEternal has this feature and it works fine with all mods that are 'automatic fuel' style.

**Comment by TastyChickenLegs** [comment]
Let me check on that.  I will test this today and let you know.

**Comment by TastyChickenLegs** [comment]
I fixed this in version 2.2.0 uploaded this morning.  Thanks again for the detailed description.
