### ISSUE TITLE
Smelter not working

### ISSUE THREAD

**Issue by andras1984** [TastyChickenLegs/NoSmokeStayLit#5]
Switched to NoSmokeStayLit from FuelEternal, smelter has coal and ore, but doesn't do anything. Tried to build a new smelter from scratch outside to see if the change in the mod broke something on the existing one, newly built one outside also doesn't work. Seems that with:

Smelter Enable Smoke = true (smelter doesn't function) (made sure to build one outside so it has all the space it needs, still doesnt)
but
Smelter Enable Smoke = false (smelter does)

Tested on a dedicated server with one client connected.

Only other mods I have installed that touches smelter (as far as I know) are:

Smoothbrain-ConversionSizeAndSpeed
OdinPlus-OdinsCraftyBoxes

**Comment by TastyChickenLegs** [comment]
Yea it's a bug in the mod.  I found it yesterday.  I plan to update it today for a fix.  It's a stray line of code that was copied in when I moving functions around.  Thanks again.

**Comment by TastyChickenLegs** [comment]
New version on Nexus and Thunderstore fixes this issue. Thanks again.
