### ISSUE TITLE
No Smoke for Ovens

### ISSUE THREAD

**Issue by DANTHEEMAN90** [TastyChickenLegs/NoSmokeStayLit#6]
Hi, is it possible to have a setting to toggle smoke for Ovens please?, i can see there is config for eternal fuel but not to remove smoke?

**Comment by TastyChickenLegs** [comment]
Yea I actually have it built.   I will upload it tonight.

**Comment by TastyChickenLegs** [comment]
Ok I just updated the mod on both Nexus and Thunderstore.  Have a great night.  Let me know if you find any bugs.

**Comment by TastyChickenLegs** [comment]
So disregard.  I uploaded a version tonight and it has a bug.  I can't reproduce it and I am afraid my development environment is no longer showing errors in the logs.  I disabled the ovens for tonight.  I need to figure out why errors are not showing in my console.  Hopefully this weekend this will be resolved.

**Comment by TastyChickenLegs** [comment]
It has been fixed.  I uploaded the new version tonight.

**Comment by DANTHEEMAN90** [comment]
> It has been fixed. I uploaded the new version tonight.

Have you accidently removed Furnace and Kiln as there is now smoke and don't see option for it to be turned off?
